import Head from 'next/head'
import Slider from '@/components/LandingPage/Silder/Silder'
import Hero from '@/components/LandingPage/Hero/Hero'
import Type from '@/components/LandingPage/Type/Type'
import Muscle from '@/components/LandingPage/Muscle&Strength/Muscle'


export default function Home({data}) {
  
  return (
    <>
      <Head>
        <title>Muscle & Strength</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className='relative overflow-x-hidden' >
        
        <Hero />
        <Type/>
        <div className='md:px-16 md:py-4'>
          <Slider/>
          <Muscle muscle={data.muscle} workouts={data.workouts} articles={data.articles}/>
        </div>
        
      </main>
    </>

  )
}

export async function getServerSideProps(){
  const {default:data}=await import("/data/data.json");
  return {
    props:{
      data
    }
  }
}