import Head from 'next/head'
import Ad from '@/components/Ad/Ad'
import Navbar from '@/components/Navbar/Navbar'
import Slider from '@/components/Silder/Silder'
import Hero from '@/components/Hero/Hero'

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <main>
        <Ad />
        <Navbar />
        <Hero/>
        <Slider/>
      </main>
    </>
  )
}

export async function getServerSideProps(){
  const {default:data}=await import("/data/data.json");
  return {
    props:{
      data
    }
  }
}