import React from "react";
import Head from "next/head";


export default function SingleMuscle({target}){

    return(
        <>
            <Head>
                <title>Muscle</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                <p>{target.title}</p>
            </main>
        </>
    )
}

export async function getStaticPaths(){
    const {muscle} = await import("/data/data.json");
    const allPaths = muscle.map(el=>(
        {
            params:{
                cat:el.title
            }
        }
    ))
    
    return {
        paths:allPaths,
        fallback:false
    }
}   

export async function getStaticProps(context){
    const {muscle} = await import("/data/data.json")
    const searchedTitle = context.params.cat
    const target = muscle.find(ev=>ev.title===searchedTitle)

    if(target)
        return{
            props:{
                target
            }
        }
    return {
        notFound:true
    }
}
