import React from 'react'
import Head from 'next/head';
import Muscles from '@/components/MusclePage/Muscles/Muscles';


export default function MusclePage({muscle}){
  return (
    <>
      <Head>
        <title>Muscle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
        <Muscles muscle={muscle}/>
    </>
   
  )
}



export async function getServerSideProps(){
    const {muscle} = await import("/data/data.json");
    if(muscle){
        return {
            props:{
                muscle
            }
        }
    }else{
        return {notFound:true}
    }
}