import React from "react";
import Head from "next/head";
import SinglePost from "@/components/MusclePage/SinglePost/SinglePost";


export default function SingleMuscle({target,res}){

    return(
        <>
            <Head>
                <title>Workouts</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                <SinglePost target={target} res={res}/>
            </main>
        </>
    )
}

export async function getStaticPaths(){
    const {workouts} = await import("/data/data.json");
   
    const allPaths = workouts.map(el=>(
        {
            params:{
                cat:el.title
            }
        }
    ))
    
    return {
        paths:allPaths,
        fallback:false
    }
}   

export async function getStaticProps(context){
    const {workouts} = await import("/data/data.json");
    const req=await fetch("https://jsonplaceholder.typicode.com/comments");
    const res=await req.json();
    const searchedTitle = context.params.cat
    const target = workouts.find(ev=>ev.title===searchedTitle)

    if(target)
        return{
            props:{
                target,
                res
            }
        }
    return {
        notFound:true
    }
}
