import React from 'react'
import Head from 'next/head';
import Muscles from '@/components/MusclePage/Muscles/Muscles';


export default function MusclePage({workouts}){
  return (
    <>
      <Head>
        <title>Muscle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
        <Muscles task={workouts}/>
    </>
   
  )
}



export async function getServerSideProps(){
    const {workouts} = await import("/data/data.json");
    if(workouts){
        return {
            props:{
                workouts
            }
        }
    }else{
        return {notFound:true}
    }
}